import type { APIStudent } from "~/services/StudentService";

export const studentsData: APIStudent[] = [
  {
    id: "1",
    firstName: "Sokha",
    lastName: "Chann",
    email: "sokha.chann@example.edu",
    joinedYear: "2022",
    year: 4,
    generation: 25,
    gen: 25,
    avatar: "https://randomuser.me/api/portraits/men/31.jpg",
    bio: "Full-stack student focused on scalable web applications.",
    skill: ["Full Stack", "Frontend", "Backend"],
    projectCount: 3,
    projects: [],
    department: { id: "d1", name: "GIC", code: "GIC" },
    role: "STUDENT",
    socialLinks: [
      { name: "github", url: "https://github.com/sokha" },
      { name: "linkedin", url: "https://linkedin.com/in/sokha" },
    ],
  },
  {
    id: "2",
    firstName: "Dara",
    lastName: "Lim",
    email: "dara.lim@example.edu",
    joinedYear: "2022",
    year: 4,
    generation: 25,
    gen: 25,
    avatar: "https://randomuser.me/api/portraits/women/58.jpg",
    bio: "Frontend developer passionate about UX and component architecture.",
    skill: ["Frontend", "UI/UX"],
    projectCount: 2,
    projects: [],
    department: { id: "d1", name: "GIC", code: "GIC" },
    role: "STUDENT",
    socialLinks: [{ name: "portfolio", url: "https://dara.dev" }],
  },
  {
    id: "3",
    firstName: "Rithy",
    lastName: "Son",
    email: "rithy.son@example.edu",
    joinedYear: "2023",
    year: 3,
    generation: 26,
    gen: 26,
    avatar: "https://randomuser.me/api/portraits/men/22.jpg",
    bio: "Backend-focused student working on APIs and distributed systems.",
    skill: ["Backend", "Database Analyst", "DevOps"],
    projectCount: 4,
    projects: [],
    department: { id: "d1", name: "GIC", code: "GIC" },
    role: "STUDENT",
    socialLinks: [{ name: "github", url: "https://github.com/rithy" }],
  },
  {
    id: "4",
    firstName: "Nary",
    lastName: "Heng",
    email: "nary.heng@example.edu",
    joinedYear: "2023",
    year: 3,
    generation: 26,
    gen: 26,
    avatar: "https://randomuser.me/api/portraits/women/37.jpg",
    bio: "Cloud and DevOps learner building reliable deployment pipelines.",
    skill: ["Cloud Architect", "DevOps", "Backend"],
    projectCount: 2,
    projects: [],
    department: { id: "d1", name: "GIC", code: "GIC" },
    role: "STUDENT",
    socialLinks: [{ name: "linkedin", url: "https://linkedin.com/in/nary" }],
  },
  {
    id: "5",
    firstName: "Phearun",
    lastName: "Keo",
    email: "phearun.keo@example.edu",
    joinedYear: "2024",
    year: 2,
    generation: 27,
    gen: 27,
    avatar: "https://randomuser.me/api/portraits/men/63.jpg",
    bio: "Security-minded student interested in secure coding and networks.",
    skill: ["Cybersecurity", "Network"],
    projectCount: 1,
    projects: [],
    department: { id: "d1", name: "GIC", code: "GIC" },
    role: "STUDENT",
    socialLinks: [],
  },
  {
    id: "6",
    firstName: "Sreypov",
    lastName: "Try",
    email: "sreypov.try@example.edu",
    joinedYear: "2024",
    year: 2,
    generation: 27,
    gen: 27,
    avatar: "https://randomuser.me/api/portraits/women/65.jpg",
    bio: "Frontend and product-focused student building student tools.",
    skill: ["Frontend", "Full Stack"],
    projectCount: 3,
    projects: [],
    department: { id: "d1", name: "GIC", code: "GIC" },
    role: "STUDENT",
    socialLinks: [{ name: "portfolio", url: "https://sreypov.dev" }],
  },
];

export default studentsData;
